name: Release
on:
  release:
    types: [published]

permissions: {}

jobs:
  trigger-publish:
    name: Trigger Publish in Deploy Repo
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - name: Trigger passwordless-java publish
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          repo: bitwarden/deploy
          deployment-task: publish-passwordless-java
          deployment-environment: passwordless-java-publish
          tag: ${{ github.event.release.tag_name }}
